name: Online check Kodi official repositories

on:
  push:
    branches: [master]

jobs:
  check-repos:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        repo: ['repo-plugins', 'repo-scripts', 'repo-scrapers', 'repo-resources', 'repo-skins', 'repo-webinterfaces']
        kodi-version: ['gotham', 'helix', 'isengard', 'jarvis', 'krypton', 'leia', 'matrix', 'nexus', 'omega', 'piers']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Clone repo
        run: |
          git clone --branch=${{ matrix.kodi-version }} --depth=1 --single-branch https://github.com/xbmc/${{ matrix.repo }}.git ../repo;

      - name: Run addon checker against the cloned repo
        run: |
          python -m kodi_addon_checker --branch=${{ matrix.kodi-version }} ../repo;
